### ISSUE TITLE
Add missing realms

### ISSUE THREAD

**Issue by Brett-Parker** [justindwyer6/rolling-realms#72]
Currently missing realms are;

**Base Game**
The Society
Pendulum
https://www.dropbox.com/sh/f2tekc23yvb27w3/AAA8nHRK3QdL3toUvEobmY0ka/Rolling%20Realms/Rulebooks?dl=0&preview=RRealms_Rulebook_r6.pdf&subfolder_nav_tracking=1

**Promos**
Rolling Realms : https://store.stonemaiergames.com/products/rolling-realms-rolling-realms-promo-pack
Terra Mystica: https://store.stonemaiergames.com/products/terra-mystica-rolling-realms-promo-pack

**Comment by abrad45** [comment]
Hey @Brett-Parker -- @justindwyer6 and I have been working on this for a few months (after Justin knocked the initial implementation out of the park before it was a retail release). Considering that retail release, Stonemaier games has asked us to keep this implementation to the PnP version that existed prior to the game being manufactured for sale. Since we can't actually implement any of the realms or realm changes you note here, we'll use this issue as a way to track progress on a goal we can achieve: making a disclaimer in the readme to ensure it's clearer a. that we won't be doing this, and b. why we won't be doing this.

Thanks for your passion and interest in the project. If you're interested in playing those realms yourself or with a small group of friends, this code is open source and nothing stops you from forking or modifying it as you wish, but as we understand it, this would need to be for personal use, not distributing publicly on github as it could cannibalize sales of what is now a Stonemaier product.

Hope this helps :)
